version: "3"
services:
  app:
    restart: on-failure
    build: .
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: 8090
      DATABASE_URL: postgresql://user:pass@postgres:5432/db
    ports:
      - "8090:8090"
    command: npm run start
    volumes:
      - .:/app/

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
  
  postgres_test:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db_test